name: GitHub Actions
on: [push]
env:
  APP_IMAGE: keboola/app-acme-anvil-service
  KBC_DEVELOPERPORTAL_APP: keboola-test.app-acme-anvil-service
  KBC_DEVELOPERPORTAL_USERNAME: keboola-test+test_app_acme_anvil_service
  KBC_DEVELOPERPORTAL_VENDOR: keboola-test
  KBC_DEVELOPERPORTAL_PASSWORD: ${{ secrets.KBC_DEVELOPERPORTAL_PASSWORD }}  
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Print Docker version
        run: |
          docker -v
      - name: Build image and run tests
        run: |
          docker build -t $APP_IMAGE .
          docker run -e TEST_VAR $APP_IMAGE composer ci
      - name: Push image to ECR
        run: |
           docker pull quay.io/keboola/developer-portal-cli-v2:latest
           export REPOSITORY=`docker run --rm -e KBC_DEVELOPERPORTAL_USERNAME -e KBC_DEVELOPERPORTAL_PASSWORD -e KBC_DEVELOPERPORTAL_URL quay.io/keboola/developer-portal-cli-v2:latest ecr:get-repository $KBC_DEVELOPERPORTAL_VENDOR $KBC_DEVELOPERPORTAL_APP`
           docker tag $APP_IMAGE:latest $REPOSITORY:test
           eval $(docker run --rm -e KBC_DEVELOPERPORTAL_USERNAME -e KBC_DEVELOPERPORTAL_PASSWORD -e KBC_DEVELOPERPORTAL_URL quay.io/keboola/developer-portal-cli-v2:latest ecr:get-login $KBC_DEVELOPERPORTAL_VENDOR $KBC_DEVELOPERPORTAL_APP)
           docker push $REPOSITORY:test
           docker pull quay.io/keboola/syrup-cli:latest
      - name: Deploy
        if: startsWith(github.ref, 'refs/tags/')
        run: ./deploy.sh
